version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - foodienet
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - foodienet

  mysql:
  image: mysql:8
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: ofBx5fvHxaamiwrfsdbJIaql2WxUhafBI
    MYSQL_DATABASE: railway
    MYSQL_USER: root
    MYSQL_PASSWORD: ofBx5fvHxaamiwrfsdbJIaql2WxUhafBI
  ports:
    - "3306:3306"
  networks:
    - foodienet

networks:
  foodienet: